DECLARE_POINTERS(IEncoder)
DECLARE_POINTERS(IEncoderController)
DECLARE_POINTERS(IEncoderView)

namespace AES
{
    DECLARE_POINTERS(IAESEncoder);
    DECLARE_POINTERS(IAESEncoderController);
    DECLARE_POINTERS(IAESEncoderView);
}